name: CI

on:
  push:
    branches:
      - v4

  pull_request:
    branches:
      - v4

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        run: corepack enable

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run prettier
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        run: corepack enable

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run test cases
        run: pnpm test:c

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        run: corepack enable

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build NutUI
        run: pnpm build

      - name: Build NutUI-Taro
        run: pnpm build:taro:vue

      - name: Build NutUI Demo
        run: pnpm build:site

      - name: Build NutUI-Taro Demo
        run: pnpm build:taro:h5
