name: Release NutUI Beta

on:
  workflow_dispatch:

jobs:
  publish-beta:
    if: github.repository == 'jdf2e/nutui'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Build NutUI Vue
        run: pnpm build

      - name: Publish NutUI Vue
        run: pnpm --dir ./publish/nutui publish:beta --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true

      - name: Build NutUI Vue Taro
        run: pnpm build:taro

      - name: Publish NutUI Vue Taro
        run: pnpm --dir ./publish/nutui-taro publish:beta --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
