name: Release NutUI Beta

on:
  workflow_dispatch:

jobs:
  publish-beta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      
      - name: Build NutUI Vue
        run: pnpm build

      - name: Publish NutUI Vue
        run: pnpm --dir ./publish/nutui publish --tag=beta --access=public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true

      - name: Build NutUI Vue Taro
        run: pnpm build:taro:vue

      - name: Publish NutUI Vue Taro
        run: pnpm --dir ./publish/nutui-taro publish --tag=beta --access=public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
