name: sync to pkg branch

permissions:
  contents: write

on:
  push:
    branches:
      - v4 # default branch

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build @nutui/nutui
        run: pnpm build
      
      - name: Build @nutui/nutui-taro
        run: pnpm build:taro

      - name: Sync
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: pkg # action 应该部署到的分支 。
          folder: publish #操作应该部署的文件夹 。
          clean: true
          target-folder: publish
          git-config-name: github-actions
          git-config-email: action@github.com
