name: Sync to Gitee、Gitcode

on:
  push:
    branches: [next]

jobs:
  deploy-site-sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:jdf2e/nutui.git
          destination-repo: git@gitee.com:jd-platform-opensource/nutui.git
    steps:
      - name: Sync to Gitcode
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:jdf2e/nutui.git
          destination-repo: git@gitcode.net:jd/nutui.git
