name: CI

on:
  push:
    branches:
      - v4

  pull_request:
    branches:
      - v4

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install pnpm
      run: corepack enable

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run test cases
      run: npm run test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install pnpm
      run: corepack enable

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Build NutUI
      run: npm run build

    - name: Build NutUI-Taro
      run: npm run build:taro:vue

    - name: Build NutUI Demo
      run: npm run build:site

    - name: Build NutUI-Taro Demo
      run: npm run build:taro:h5